name: Publish prerelease

on:
  push:
    branches:
      - beta
      - alpha

permissions:
  contents: write
  pull-requests: write

jobs:
  prerelease:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org
          cache: npm

      - run: npm ci
      - run: npm run build

      - name: Enter prerelease mode
        run: |
          # 检查 pre.json 是否存在，防止重复 enter 报错
          if [ -f ".changeset/pre.json" ]; then
            echo "Already in pre mode."
          else
            if [[ "${GITHUB_REF_NAME}" == "beta" ]]; then
              npx changeset pre enter beta
            else
              npx changeset pre enter alpha
            fi
          fi

      - name: Create Release PR or Publish prerelease
        id: changesets
        uses: changesets/action@v1
        with:
          publish: npm run changeset:release
          createGithubReleases: false
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create npm Tarball
        if: steps.changesets.outputs.published == 'true'
        id: pack
        run: |
          # 使用 --silent 减少干扰，并只取最后一行作为文件名
          TGZ_FILE=$(npm pack --silent | tail -n 1)
          echo "TGZ_PATH=$TGZ_FILE" >> $GITHUB_OUTPUT

          # 获取版本号
          V=$(node -p "require('./package.json').version")
          echo "REAL_TAG=v$V" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        if: steps.changesets.outputs.published == 'true'
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.pack.outputs.REAL_TAG }}
          generate_release_notes: true
          prerelease: true
          files: ${{ steps.pack.outputs.TGZ_PATH }}
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
